### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by EmpRamses** [poojahira/gtsrb-pytorch#1]
When I run the code as your instruction after preparing data, I got a runtime error caused by the "stn" function. 

> Traceback (most recent call last):
  File "main.py", line 124, in <module>
    train(epoch)
  File "main.py", line 86, in train
    output = model(data)
  File "/home/wzg13/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wzg13/trojai/gtsrb-pytorch/model.py", line 61, in forward
    x = self.stn(x)
  File "/home/wzg13/trojai/gtsrb-pytorch/model.py", line 55, in stn
    grid = F.affine_grid(theta, x.size())
  File "/home/wzg13/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 2615, in affine_grid
    return vision.affine_grid_generator(theta, size)
  File "/home/wzg13/.local/lib/python3.7/site-packages/torch/nn/_functions/vision.py", line 10, in affine_grid_generator
    ret = torch.cudnn_affine_grid_generator(theta, N, C, H, W)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Following a same question posted on StackOverflow, I added `.cuda()` behind definitions of variables in the "stn" function. But the runtime error still occur. I have no idea what problem have happened in the model.

**Comment by huagl** [comment]
@EmpRamses I got the similar problem! Did you fixed it?

**Comment by poojahira** [comment]
Possible fix here? : https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-execution-failed/31169/8
